import type { TemplateRecord } from '@/lib/types'

const JAVANESE_GOLD: TemplateRecord = {
  id: 'javanese-gold',
  name: 'Javanese Gold',
  slug: 'javanese-gold',
  category: 'tradisional',
  description: 'Nuansa Jawa klasik dengan aksen emas — cocok untuk akad adat dan resepsi bernuansa tradisional.',
  thumbnail_url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=400&h=600&fit=crop',
  status: 'active',
  sort_order: 1,
  usage_count: 0,
  price: 0,
  required_package: 'all',
  created_at: '2026-01-01T00:00:00.000Z',
  updated_at: '2026-01-01T00:00:00.000Z',
  config: {
    meta: {
      color_scheme: {
        primary: '#1a4a1a',
        accent: '#d4af37',
        text: '#ffffff',
        background: '#0f2d0f',
      },
      font: {
        heading: 'Cinzel',
        body: 'Cormorant Garamond',
        heading_scale: 1.0,
        body_scale: 1.0,
      },
      component_style: {
        button: 'outlined',
        border: 'sharp',
        ornament: 'classic',
      },
    },
    loading: {
      background_color: '#1a4a1a',
      text: 'Membuka undangan...',
      animation: 'pulse',
      variant: 'elegant-spinner',
      duration_ms: 2500,
      accent_color: '#d4af37',
      text_color: '#ffffff',
      show_progress: false,
      font_family: 'Cormorant Garamond',
      text_size: 'base',
      animation_speed: 'normal',
      bg_type: 'solid',
    },
    opening: {
      type: 'fade-reveal',
      duration_ms: 3000,
      show_opening: true,
      subtitle: 'The Wedding of',
      button_text: 'Buka Undangan',
      invitation_text: 'Anda diundang ke pernikahan',
      show_guest_name: true,
      cover_photo_url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&h=1200&fit=crop',
      cover_photo_opacity: 35,
      cover_photo_position: 'center',
      cover_photo_display: 'background',
      cover_gradient_height: 80,
      decoration_assets: [],
    },
    music: {
      enabled: true,
      url: 'https://zwburqdtpxvqotpcunzh.supabase.co/storage/v1/object/public/uploads/music/iqro.mp3',
      title: 'Iqro',
      autoplay: true,
      volume: 0.3,
      loop: true,
      player_style: 'pill',
      player_position: 'bottom-right',
      player_animation: 'fade-slide',
      show_title: true,
      player_size: 'md',
    },
    sections: [
      {
        id: 'hero-1',
        type: 'hero',
        order: 1,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        transition_in: 'fade',
        transition_out: 'slide-up',
        user_fields: ['bride_name', 'groom_name', 'tagline', 'couple_photo_url'],
        style_variant: 'default',
        hero_bismillah: 'arabic',
        hero_title_size: 36,
        hero_and_size: 22,
        hero_tagline_size: 11,
        hero_show_scroll: true,
        hero_text_shadow: true,
      },
      {
        id: 'quote-1',
        type: 'quote',
        order: 2,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['quote_arabic', 'quote_translation', 'quote_source'],
        text_align: 'center',
      },
      {
        id: 'profiles-1',
        type: 'profiles',
        order: 3,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        transition_in: 'fade',
        transition_out: 'slide-up',
        user_fields: ['groom_photo_url', 'bride_photo_url', 'groom_bio', 'bride_bio', 'groom_parents', 'bride_parents'],
        style_variant: 'default',
      },
      {
        id: 'countdown-1',
        type: 'countdown',
        order: 4,
        enabled: true,
        background: {
          type: 'image',
          url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=1200&fit=crop',
          overlay_opacity: 0.6,
        },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['akad'],
        style_variant: 'cinematic',
      },
      {
        id: 'events-1',
        type: 'events',
        order: 5,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['akad', 'resepsi'],
      },
      {
        id: 'story-1',
        type: 'story',
        order: 6,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['story_title', 'story_text', 'story_chapters', 'story_timeline'],
      },
      {
        id: 'video-1',
        type: 'video',
        order: 7,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['video_embed_url', 'video_caption'],
      },
      {
        id: 'gallery-1',
        type: 'gallery',
        order: 8,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['gallery_photos'],
      },
      {
        id: 'gift-1',
        type: 'gift',
        order: 9,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['gift_accounts'],
        gift_show_logo: true,
        gift_proof_enabled: true,
      },
      {
        id: 'gift-registry-1',
        type: 'gift-registry',
        order: 10,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['gift_registry'],
      },
      {
        id: 'rsvp-1',
        type: 'rsvp',
        order: 11,
        enabled: true,
        background: {
          type: 'image',
          url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&h=1200&fit=crop',
          overlay_opacity: 0.65,
        },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'wishes-1',
        type: 'wishes',
        order: 12,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'livestream-1',
        type: 'livestream',
        order: 13,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'ig-story-1',
        type: 'ig-story',
        order: 14,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['ig_story_image_url'],
      },
      {
        id: 'qrcode-1',
        type: 'qrcode',
        order: 15,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['qr_target_url', 'qr_label'],
      },
      {
        id: 'closing-1',
        type: 'closing',
        order: 16,
        enabled: true,
        background: {
          type: 'image',
          url: 'https://images.unsplash.com/photo-1606216794079-73f85bbd57d5?w=800&h=1200&fit=crop',
          overlay_opacity: 0.55,
        },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['closing_text', 'thank_you_message'],
        style_variant: 'cinematic',
      },
    ],
  },
}

export default JAVANESE_GOLD
