import type { TemplateRecord } from '@/lib/types'

const MIDNIGHT_LUXE: TemplateRecord = {
  id: 'midnight-luxe',
  name: 'Midnight Luxe',
  slug: 'midnight-luxe',
  category: 'modern',
  description: 'Gelap, tenang, dan mewah. Dibuat untuk resepsi malam berkelas.',
  thumbnail_url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=400&h=600&fit=crop',
  status: 'active',
  sort_order: 3,
  usage_count: 0,
  price: 0,
  required_package: 'eksklusif',
  created_at: '2026-01-01T00:00:00.000Z',
  updated_at: '2026-01-01T00:00:00.000Z',
  config: {
    meta: {
      color_scheme: {
        primary: '#0c0c0c',
        accent: '#b8977e',
        text: '#f5f0eb',
        background: '#0c0c0c',
      },
      font: {
        heading: 'Cormorant Garamond',
        body: 'Inter',
        heading_scale: 1.1,
        body_scale: 1.0,
      },
      component_style: {
        button: 'outlined',
        border: 'sharp',
        ornament: 'geometric',
      },
    },
    loading: {
      background_color: '#0c0c0c',
      text: 'Membuka undangan...',
      animation: 'pulse',
      variant: 'elegant-spinner',
      duration_ms: 2500,
      accent_color: '#b8977e',
      text_color: '#f5f0eb',
      show_progress: false,
      font_family: 'Inter',
      text_size: 'base',
      animation_speed: 'normal',
      bg_type: 'solid',
    },
    opening: {
      type: 'curtain',
      duration_ms: 3500,
      show_opening: true,
      /**
       * Satu satunya tema yang sapaannya bukan salam Islam, dan itu
       * disengaja. Dua tema lain membuka dengan Assalamualaikum karena itu
       * yang dipakai sebagian besar undangan di Indonesia. Menyeragamkan
       * ketiganya berarti pembeli non muslim harus mengganti sapaan dulu
       * sebelum undangannya terasa milik mereka. Pembeli tetap bisa
       * mengubahnya di layar Pembuka, dua duanya.
       */
      subtitle: 'Salam sejahtera untuk kita semua',
      button_text: 'Buka Undangan',
      invitation_text: 'Anda diundang ke pernikahan',
      show_guest_name: true,
      cover_photo_url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&h=1200&fit=crop',
      cover_photo_opacity: 40,
      cover_photo_position: 'center',
      cover_photo_display: 'background',
      cover_gradient_height: 90,
      decoration_assets: [],
    },
    music: {
      enabled: true,
      url: 'https://zwburqdtpxvqotpcunzh.supabase.co/storage/v1/object/public/uploads/music/iqro.mp3',
      title: 'Iqro',
      autoplay: true,
      volume: 0.3,
      loop: true,
      player_style: 'pill',
      player_position: 'bottom-right',
      player_animation: 'fade-slide',
      show_title: true,
      player_size: 'md',
    },
    sections: [
      {
        id: 'hero-1',
        type: 'hero',
        order: 1,
        enabled: true,
        background: { type: 'color', value: '#0c0c0c' },
        transition_in: 'zoom-in',
        transition_out: 'fade',
        user_fields: ['bride_name', 'groom_name', 'tagline', 'couple_photo_url'],
        style_variant: 'default',
        hero_bismillah: 'arabic',
        hero_title_size: 40,
        hero_and_size: 20,
        hero_tagline_size: 11,
        hero_show_scroll: true,
        hero_text_shadow: true,
      },
      {
        id: 'quote-1',
        type: 'quote',
        order: 2,
        enabled: true,
        background: { type: 'color', value: '#111111' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['quote_arabic', 'quote_translation', 'quote_source'],
        text_align: 'center',
      },
      {
        id: 'profiles-1',
        type: 'profiles',
        order: 3,
        enabled: true,
        background: { type: 'color', value: '#0c0c0c' },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['groom_photo_url', 'bride_photo_url', 'groom_bio', 'bride_bio', 'groom_parents', 'bride_parents'],
        style_variant: 'default',
      },
      {
        id: 'countdown-1',
        type: 'countdown',
        order: 4,
        enabled: true,
        background: {
          type: 'image',
          url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=1200&fit=crop',
          overlay_opacity: 0.7,
        },
        transition_in: 'zoom-in',
        transition_out: 'fade',
        user_fields: ['akad'],
        style_variant: 'cinematic',
      },
      {
        id: 'events-1',
        type: 'events',
        order: 5,
        enabled: true,
        background: { type: 'color', value: '#0c0c0c' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['akad', 'resepsi'],
      },
      {
        id: 'story-1',
        type: 'story',
        order: 6,
        enabled: true,
        background: { type: 'color', value: '#111111' },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['story_title', 'story_text', 'story_chapters', 'story_timeline'],
      },
      {
        id: 'video-1',
        type: 'video',
        order: 7,
        enabled: true,
        background: { type: 'color', value: '#0c0c0c' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['video_embed_url', 'video_caption'],
      },
      {
        id: 'gallery-1',
        type: 'gallery',
        order: 8,
        enabled: true,
        background: { type: 'color', value: '#111111' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['gallery_photos'],
      },
      {
        id: 'gift-1',
        type: 'gift',
        order: 9,
        enabled: true,
        background: { type: 'color', value: '#0c0c0c' },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['gift_accounts'],
        gift_show_logo: true,
        gift_proof_enabled: true,
      },
      {
        id: 'gift-registry-1',
        type: 'gift-registry',
        order: 10,
        enabled: true,
        background: { type: 'color', value: '#111111' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['gift_registry'],
      },
      {
        id: 'rsvp-1',
        type: 'rsvp',
        order: 11,
        enabled: true,
        background: {
          type: 'image',
          url: 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800&h=1200&fit=crop',
          overlay_opacity: 0.75,
        },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'wishes-1',
        type: 'wishes',
        order: 12,
        enabled: true,
        background: { type: 'color', value: '#0c0c0c' },
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'livestream-1',
        type: 'livestream',
        order: 13,
        enabled: true,
        background: { type: 'color', value: '#111111' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'ig-story-1',
        type: 'ig-story',
        order: 14,
        enabled: true,
        background: { type: 'color', value: '#0c0c0c' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['ig_story_image_url'],
      },
      {
        id: 'qrcode-1',
        type: 'qrcode',
        order: 15,
        enabled: true,
        background: { type: 'color', value: '#111111' },
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['qr_target_url', 'qr_label'],
      },
      {
        id: 'closing-1',
        type: 'closing',
        order: 16,
        enabled: true,
        background: {
          type: 'image',
          url: 'https://images.unsplash.com/photo-1509927083803-4bd519298ac4?w=800&h=1200&fit=crop',
          overlay_opacity: 0.7,
        },
        transition_in: 'zoom-in',
        transition_out: 'fade',
        user_fields: ['closing_text', 'thank_you_message'],
        style_variant: 'cinematic',
      },
    ],
  },
}

export default MIDNIGHT_LUXE
